# Generated by Django 5.0.7 on 2024-08-14 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
