# Generated by Django 5.0.7 on 2024-08-13 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
