# Generated by Django 5.0.7 on 2024-08-14 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('q', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='code',
            field=models.IntegerField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
